<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>True</BadObjectCC><Advice>This is likely due to bad object CC. Check the Summary and Broken Mods section in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 00:28:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>flauschtrud_neighborhoodstories_marriage.py:158</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>[BE Interceptor] BE intercepted this error from a separate mod log so that it can scan for the issue. (TypeError: object of type 'NoneType' has no len())&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_chapter.py", line 382, in &lt;genexpr&gt;&#13;&#10;  File "J:\flauschtrud\Documents\USB Backup\Python Workspace\My Script Mods\NeighborhoodStoriesMarriage\Scripts\flauschtrud_neighborhoodstories_marriage.py", line 158, in reserved_household_slots&#13;&#10;TypeError: object of type 'NoneType' has no len()rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 00:53:02</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>flauschtrud_neighborhoodstories_marriage.py:158</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>Exception while updating story progression service.:  (TypeError: object of type 'NoneType' has no len())&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_chapter.py", line 382, in &lt;genexpr&gt;&#13;&#10;  File "J:\flauschtrud\Documents\USB Backup\Python Workspace\My Script Mods\NeighborhoodStoriesMarriage\Scripts\flauschtrud_neighborhoodstories_marriage.py", line 158, in reserved_household_slots&#13;&#10;TypeError: object of type 'NoneType' has no len()rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 01:33:11</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>flauschtrud_neighborhoodstories_marriage.py:158</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>Exception while updating story progression service.:  (TypeError: object of type 'NoneType' has no len())&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_chapter.py", line 382, in &lt;genexpr&gt;&#13;&#10;  File "J:\flauschtrud\Documents\USB Backup\Python Workspace\My Script Mods\NeighborhoodStoriesMarriage\Scripts\flauschtrud_neighborhoodstories_marriage.py", line 158, in reserved_household_slots&#13;&#10;TypeError: object of type 'NoneType' has no len()rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 01:57:13</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>flauschtrud_neighborhoodstories_marriage.py:158</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>Exception while updating story progression service.:  (TypeError: object of type 'NoneType' has no len())&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_chapter.py", line 382, in &lt;genexpr&gt;&#13;&#10;  File "J:\flauschtrud\Documents\USB Backup\Python Workspace\My Script Mods\NeighborhoodStoriesMarriage\Scripts\flauschtrud_neighborhoodstories_marriage.py", line 158, in reserved_household_slots&#13;&#10;TypeError: object of type 'NoneType' has no len()rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 02:23:17</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>posture.py:2471</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: Posture Exit(posture_CarryNothing:4420) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 327656681793758504. Last affordance: &lt;class 'sims4.tuning.instances.NPCLeaveLotNow_NPC_WaveGoodBye'&gt;. Current lot description id: 118800.)&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2471, in _do_end&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2458, in get_endRuntimeError: Posture Exit(posture_CarryNothing:4420) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 327656681793758504. Last affordance: &lt;class 'sims4.tuning.instances.NPCLeaveLotNow_NPC_WaveGoodBye'&gt;. Current lot description id: 118800.rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>f44edd7fb9b4b45a6584c5f9</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-22 02:23:41</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>posture.py:2471</categoryid><desyncid>f44edd7fb9b4b45a6584c5f9</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (RuntimeError: Posture Exit(posture_CarryNothing:4528) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 327656681843109307. Last affordance: &lt;class 'sims4.tuning.instances.NPCLeaveLotNow_NPC_WaveGoodBye'&gt;. Current lot description id: 118800.)&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2471, in _do_end&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture.py", line 2458, in get_endRuntimeError: Posture Exit(posture_CarryNothing:4528) called multiple times without a paired entry or never called (PrimitiveCreated: True). Sim ID: 327656681843109307. Last affordance: &lt;class 'sims4.tuning.instances.NPCLeaveLotNow_NPC_WaveGoodBye'&gt;. Current lot description id: 118800.rtim=0&#13;&#10;Client Session Time: 17.11&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>