<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>False</BadObjectCC><Advice>Not available. More info may be in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:02:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:02:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:03:20</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:06:42</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:10:54</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 77, in _run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 174, in _run_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\venue_tuning.py", line 1341, in summon_npcs&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\npc_summoning.py", line 101, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_director.py", line 1832, in handle_sim_summon_request&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File ".\WickedWhims_v177c\turbolib2\events\sims.py", line 105, in _turbolib_sim_instance_spawn&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 526, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:10:56</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 77, in _run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 174, in _run_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\venue_tuning.py", line 1341, in summon_npcs&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\npc_summoning.py", line 101, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_director.py", line 1832, in handle_sim_summon_request&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File ".\WickedWhims_v177c\turbolib2\events\sims.py", line 105, in _turbolib_sim_instance_spawn&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 526, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:10:57</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 77, in _run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 174, in _run_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\venue_tuning.py", line 1341, in summon_npcs&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\npc_summoning.py", line 101, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_director.py", line 1832, in handle_sim_summon_request&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File ".\WickedWhims_v177c\turbolib2\events\sims.py", line 105, in _turbolib_sim_instance_spawn&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 526, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:17:33</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 176, in _behavior_element&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 697, in _do_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 690, in run_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 228, in switch_sim_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 285, in switch_sim_from_household_to_target_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 385, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1048, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:20:55</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:20:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:21:07</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:21:07</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:23:35</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:46:30</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_spin.py", line 100, in _turbolib_on_late_zone_load&#13;&#10;  File "src/control_any_sim/util/inject.py", line 10, in _inject&#13;&#10;  File "src/control_any_sim/util/game_events.py", line 84, in canys_zone_do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1654, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1046, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 363, in set_active_sim_by_id&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:47:00</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 77, in _run_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_interactions.py", line 174, in _run_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\venue_tuning.py", line 1341, in summon_npcs&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\venues\npc_summoning.py", line 101, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_director.py", line 1832, in handle_sim_summon_request&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File ".\WickedWhims_v177c\turbolib2\events\sims.py", line 105, in _turbolib_sim_instance_spawn&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 526, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:47:27</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:53:01</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 176, in _behavior_element&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 697, in _do_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 690, in run_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 228, in switch_sim_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 285, in switch_sim_from_household_to_target_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 385, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1048, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:55:34</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:55:34</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:57:54</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:58:47</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProC2x1_01:0x07d412256e23471b: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:58:50</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProC2x1_01:0x07d412256e23471b: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 21:58:54</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProC2x1_01:0x07d412256e23471b: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:01:14</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:18:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:18:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:18:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:18:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:20:32</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3243, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_career\mc_career_inject.py", line 203, in inject_handle_career_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 4032, in handle_career_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3988, in evaluate_career_performance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3627, in _promote&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3741, in _promote_within_track&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3563, in _change_level_within_track&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:20:32</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:21:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:39:29</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:39:29</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:40:01</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 176, in _behavior_element&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 697, in _do_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 690, in run_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 228, in switch_sim_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 285, in switch_sim_from_household_to_target_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 385, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1048, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:52:06</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 176, in _behavior_element&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 697, in _do_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 690, in run_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 228, in switch_sim_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 285, in switch_sim_from_household_to_target_household&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 385, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1048, in add_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:54:35</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:54:35</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:20</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:23</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\ui_commands.py", line 29, in ui_dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog_service.py", line 211, in dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog.py", line 513, in respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_service.py", line 449, in _on_career_event_multi_sim_response&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2439, in on_career_event_declined&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:23</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\ui_commands.py", line 29, in ui_dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog_service.py", line 211, in dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog.py", line 513, in respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_service.py", line 452, in _on_career_event_multi_sim_response&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2439, in on_career_event_declined&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:23</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\ui_commands.py", line 29, in ui_dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog_service.py", line 211, in dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog.py", line 513, in respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_service.py", line 452, in _on_career_event_multi_sim_response&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2439, in on_career_event_declined&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:58</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:58</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:58</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:58</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:56:58</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:57:35</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2199, in _late_for_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>5ca1fec10a66dc2565a58c80</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-15 22:57:38</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>5ca1fec10a66dc2565a58c80</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.97&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>