<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>False</BadObjectCC><Advice>Not available. More info may be in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>fb2700bc5954eba065a9235c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-18 15:59:02</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>trait_tracker.py:1738</categoryid><desyncid>fb2700bc5954eba065a9235c</desyncid><systemconfig/><screenshot/><desyncdata>[BE Interceptor] BE intercepted this error from a separate mod log so that it can scan for the issue. (AttributeError: 'NoneType' object has no attribute 'min_lod_value')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\interaction_commands.py", line 988, in select_choice&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 263, in select_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\choices.py", line 254, in select&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 243, in test_and_execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 224, in execute&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 192, in execute_interaction&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 166, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 157, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 595, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 303, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_ops.py", line 389, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\occult\sim_info_with_occult_tracker.py", line 74, in add_trait&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\traits\trait_tracker.py", line 84, in add_trait&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\LifeMilestones\Scripts\Lumpinou_LifeMilestones_Injector\Lumpinou_Injector.py", line 6, in _inject&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\LifeMilestones\Scripts\Lumpinou_LifeMilsetones_Injections.py", line 372, in lumpinou_milsestones_ckeck_on_game_adding_trait&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\traits\trait_tracker.py", line 654, in _add_trait&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cas\mc_cas_inject.py", line 180, in inject_can_add_trait&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\traits\trait_tracker.py", line 426, in can_add_trait&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\traits\trait_tracker.py", line 1738, in _has_valid_lod&#13;&#10;AttributeError: 'NoneType' object has no attribute 'min_lod_value'rtim=0&#13;&#10;Client Session Time: 23.65&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,104,0,5617&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>fb2700bc5954eba065a9235c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-18 17:53:16</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>fb2700bc5954eba065a9235c</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProQA4x1_01:0x0a1c12291aab5b7b: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 23.65&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,104,0,5617&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>fb2700bc5954eba065a9235c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-18 17:53:20</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>fb2700bc5954eba065a9235c</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProQA4x1_01:0x0a1c12291aab5b7b: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 23.65&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,104,0,5617&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>